### ISSUE TITLE
problem with append

### ISSUE THREAD

**Issue by AmirHossein207** [LucoDevro/sequentialScanner#1]
Hello,
I get this error anywhere append is used when running the Overhead script. can you help me with it?
"Error using append (line 38)
Wrong number of input arguments for obsolete
matrix-based syntax.

Error in sequentialScanner (line 34)
        fprintf(append('Entering loop
        ',num2str(j),'...\n'));

Error in sequentialScannerOverhead (line 45)
res=sequentialScanner(model,genesel,nGenes,prodRxn,MM,upregFactor,selectedPercentile,muThreshold,optimVar); "

**Comment by LucoDevro** [comment]
Hi,

I just checked; I doesn't throw errors in my setup: it nicely works through loop 1 and starts loop 2.
Can you provide more information about yours (Matlab version? Any changes in the scripts? Example code?)?

Does it work when you comment that print command?

**Comment by AmirHossein207** [comment]
sorry for the bother. I realized my Matlab version (2018b) does not support the function "append". so, I used another computer with Matlab  2022a. It's running smoothly.
thank you very much
Also, I tried to use the E.coli model iJO1366. There was a problem with "model.geneNames" in iJO1366 it's "model.genes". other than that everything works just fine.

**Comment by LucoDevro** [comment]
No worries, I'm happy that it works well. Thanks for using this code.

About geneNames: that's possible. Not all metabolic models are consistent in what to put in the `genes` field. I manually added a `geneNames` field to the iYO844 and used that.

Closing this issue.
